### ISSUE TITLE
PropertiesTester::test

### ISSUE THREAD

**Issue by Ori-Libhaber** [rlogiacco/SmartUnit#8]
PropertiesTester::test at line 183 method makes no use of the value parameter, as far as I understand it should pass this value to the accessor method.

**Comment by rlogiacco** [comment]
I believe you are right... I'll have a look later today at this

**Comment by rlogiacco** [comment]
I've committed a few changes and apparently everything is fine, but I would ask you for a confirmation before publishing a new release: can you validate the current sources, please?

**Comment by Ori-Libhaber** [comment]
Hi,
Thank you for looking into this!
Will do asap!

**Comment by Ori-Libhaber** [comment]
Looks good!
I'll need to check it again against real test code to make sure but as far as it seems, this should do the trick!
